name: Manual run

on:
  workflow_dispatch:
    inputs:
      jahia_image:
        description: 'Jahia Image'
        required: true
        default: 'ghcr.io/jahia/jahia-ee-dev:8-SNAPSHOT'
      manifest:
        description: 'Provisioning manifest. Can be a local repository file in the tests folder or a publicly accessible link'
        required: true
        default: 'provisioning-manifest-snapshot.yml'

jobs:
  integration-tests-standalone:
    name: Manual run - ${{ github.events.inputs.jahia_image }}
    uses: Jahia/jahia-modules-action/.github/workflows/reusable-integration-tests.yml@v2
    secrets: inherit
    with:
      jahia_image: ${{ github.events.inputs.jahia_image }}
      module_id: jahia-oauth
      should_skip_testrail: true
      pagerduty_skip_notification: true
      provisioning_manifest: ${{ github.events.inputs.manifest }}
      artifact_prefix: oauth
      module_branch: ${{ github.ref }}
