name: Nightly Tests (Jahia Release)

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 1 * * *'

jobs:
  integration-tests:
    uses:  Jahia/jahia-modules-action/.github/workflows/reusable-integration-tests.yml@v2
    secrets: inherit
    with:
      jahia_image: jahia/jahia-ee:8
      module_id: jahia-oauth
      testrail_project: Jahia OAuth
      pagerduty_incident_service: jahia-oauth-JahiaRL
      provisioning_manifest: provisioning-manifest-snapshot.yml
      artifact_prefix: oauth
